

class Novels{
  late int? novelID;
  late String? novelName;
  late String? novelGenre;
  late String? novelAuthor;
  late String? novelRating;
  late int? novelHalaman;
  late String? novelSinopsis;
  late String? novelPic;
  late String? novelDate;
  late String? novelContent;


  Novels({this.novelID, this.novelName, this.novelGenre, this.novelAuthor,
    this.novelRating,this.novelHalaman, this.novelSinopsis, this.novelPic,
  this.novelDate, this.novelContent});

  List<Novels> novel =[
    Novels(novelID: 1, novelName: "Dua Garis Biru", novelGenre: "Romance", novelAuthor: "Lucia Priandarini",
    novelRating: "4.2", novelHalaman: 206, novelSinopsis: "Bima dan Dara, di usianya yang masih sangat belia harus mempertanggungjawabkan perbuatan mereka. Sebuah kesalahan yang besar membuat kehidupan mereka tak lagi sama. Masa depan mereka pun dipertaruhkan. Hamil muda di luar nikah, Dara menghadapi banyak dilema. Dia bingung dengan bagaimana caranya dia bisa menghadapi orangtuanya. Khawatir dengan impiannya untuk kuliah di Korea yang mungkin tak akan terwujud. Menghadapi teman-teman sekolahnya. Serta tentu saja soal bagaimana ia menyikapi hubungannya dengan Bima. Bima yang cenderung cuek dan bersikap masa bodoh, mau tak mau harus ikut memikirkan masa depannya dan masa depan Dara. Terlepas dari usianya yang masih muda, dia akan menjadi seorang ayah. Namun, tentu saja menghadapi kenyataan dan menanggung konsekuensi yang ada tidaklah mudah.",
    novelPic: "assets/romance1.png", novelDate: "Juli 2019", novelContent: "abc"),
    Novels(novelID: 2, novelName: "Ada Apa Dengan Cinta", novelGenre: "Romance", novelAuthor: "Silvarani",
        novelRating: "4.5", novelHalaman: 196, novelSinopsis: "Apa lagi yang kurang dalam hidup Cinta? Ia punya keluarga yang bahagia, popularitas di sekolah, banyak pengagum, dan yang paling penting, ia punya sahabat-sahabatnya. Alya, Maura, Milly, dan Karmen membuat hari-harinya selalu berwarna. Mereka adalah pusat dunia Cinta.Sampai suatu hari, ia berkenalan dengan Rangga, cowok jutek dan penyendiri yang lebih suka berteman dengan buku daripada manusia. Ternyata mereka sama-sama menyukai puisi, minat yang tak bisa Cinta bagi dengan keempat sahabatnya. Dan perlahan hal itu membawa perubahan pada dirinya, membuat orang-orang di sekitarnya bertanya-tanya, ada apa dengan Cinta?",
        novelPic: "assets/romance2.png", novelDate: "April 2016", novelContent: "adadada"),
    Novels(novelID: 3, novelName: "Cinta Yang Tak Biasa", novelGenre: "Romance", novelAuthor: "Natta Reza",
        novelRating: "4.2", novelHalaman: 240, novelSinopsis: "Untuk sesuatu yang sangat kita cintai, seringkali kita rela merasakan cobaan terberat dalam hidup. Dari susah hingga senang. Jatuh untuk bangun termasuk kehilangan banyak hal demi sebuah pertemuan yang berharga. Semua itu mesti dilalui untuk satu hal yang diyakini akan mengubah hidup kita : rasa cinta dari Tuhan.Natta percaya dengan mengalahkan rasa cintanya kepada manusia maka suatu saat ia akan mendapatkan cinta yang lebih besar dari Nya. Begitupun dengan Wardah yang meyakini kalau sang pemilik cinta telah menyiapkan seorang yang akan mencintainya dengan tulus dan Ridha-Nya.Lalu bagaimana Tuhan menyiapkan skenario untuk keduanya? bukalah buku ini dan ikuti setiap kisah tentang cinta yang tak biasa dalam lembarnya Untuk sesuatu yang sangat kita cintai seringkali kita rela merasakan cobaan terberat dalam hidup. Dari susah hingga senang. Jatuh untuk bangun termasuk kehilangan banyak hal demi sebuah pertemuan yang berharga. Semua itu mesti dilalui untuk satu hal yang diyakini akan mengubah hidup kita : rasa cinta dari Tuhan. Natta percaya dengan mengalahkan rasa cintanya kepada manusia maka suatu saat ia akan mendapatkan cinta yang lebih besar dari Nya. Begitupun dengan Wardah yang meyakini kalau sang pemilik cinta telah menyiapkan seorang yang akan mencintainya dengan tulus dan Ridha-Nya. Lalu bagaimana Tuhan menyiapkan skenario untuk keduanya? bukalah buku ini dan ikuti setiap kisah tentang cinta yang tak biasa dalam lembarnya…",
        novelPic: "assets/romance3.png", novelDate: "Juli 2017", novelContent: "Kehadiranku di muka bumi pada 18 Juni 1990 menjadi pelengkap kebahagiaan orangtua. Aku lahir di pulau terpencil di bagian barat Indonesia, Pulau Bangka. Sebagai daerah pertambangan, watak keras menjadi karakter khas masyarakat di sana. Kondisi lingkungan memang berpengaruh besar terhadap watak seseorang, tak terkecuali aku. Aku menghabiskan waktu kanak-kanak dengan begitu bahagia, tanpa beban. Tumbuh dalam lingkungan keluarga yang sederhana tidak menjadikanku kekurangan kasih sayang. Apalagi saat itu Ayah kerap berada di luar rumah karena pekerjaannya. Aku menikmati kehidupan penuh canda, cinta, dan perhatian yang melimpah. Apa pun keinginanku pasti mudah dipenuhi, terlebih oleh Ibu. Maklum, sebagai anak sulung kasih sayang orangtua tercurah penuh padaku. Rasanya saat kecil dulu, aku menjalani hidup tanpa beban. Menganggap kehidupan itu selamanya manis, tidak ada duka. Aku tidak pernah tahu di masa dewasa akan seperti apa. Belum menyadari bahwa hidup adalah roda kehidupan. Ada kalanya kita bahagia dan ada waktunya harus berjuang."),
    Novels(novelID: 4, novelName: "Lukacita", novelGenre: "Romance", novelAuthor: "Valerie Patkar",
        novelRating: "4.46", novelHalaman: 441, novelSinopsis: "Lukacita mengisahkan tentang dua orang pemimpi yang dikhianati oleh cita-cita mereka sendiri. Di dalam buku tersebut kita akan bertemu dengan Javier, seorang pendiri perusahaan startup dan Utara yang merupakan seorang mantan atlet catur. Salah satu kutipannya yang cukup menarik yaitu “Cita-cita mungkin bisa membuat kita terluka, tapi kita gak pernah cukup berani untuk membencinya”.",
        novelPic: "assets/romance4.png", novelDate: "Desember 2021", novelContent: 'Di depan gedung sekolah gue dulu, ada seseorang yang disebut Abang Safari. Setiap minggu, pasti adaaa aja binatang yang dia jual di gerobak kayu dengan cat warna-warni mentereng. Ada kelinci, anak ayam, ikan mas kecil di dalam plastik bening yang diisi semua binatang yang dia jual, gue paling suka keong. Tapi setiap gue bawa pulang ke rumah, keong itu cuma akan bertahan beberapa jam sebelum menghilang-meninggalkan cangkangnya, rumahnya. Keong itu berani, ya? Dia nggak pernah takut meninggalkan rumahnya meskipun banyak yang bilang dia nggak akan bertahan hidup lama kalau keluar dari cangkang. Seandainya gue bisa menjadi seberani itu. "Kami tanya sekali lagi, apa benar kamu ingin keluar dari Per- casi1 dan berhenti total dari catur?" Pandangan gue tertuju pada kipas angin yang terus memutarkan porosnya di langit-langit ru- angan itu. Sejak kedatangan gue setengah jam lalu, dia sudah ber- putar 547 kali. "Kamu ini masih muda, baru 22 tahun dan baru lulus kuliah. Anak-anak seumur kamu baru akan mulai mengejar mimpi mereka, tapi kamu malah mau berhenti dari apa yang sudah kamu bangun selama 14 tahun terakhir?” Pagi ini adalah hari yang terlalu baik untuk menyambut sebuah perpisahan. Udara nggak terlalu panas dan terik, malah sejuk dan dingin. Jalanan protokol ibu kota nggak padat seperti biasa. Angin bertiup kencang dan membuat dedaunan ke kanan dan ke kiri se- perti menari-nari.'),
    Novels(novelID: 5, novelName: "Troubled Blood", novelGenre: "Fantasy", novelAuthor: "J. K. Rowling",
        novelRating: "4.44", novelHalaman: 871, novelSinopsis: "Troubled Blood  dimulai pada bulan Agustus 2013 dan berakhir pada ulang tahun Robin yang ke-30 pada tanggal 9 Oktober 2014. Saat mengunjungi bibinya yang sakit parah, Joan di Cornwall , Strike didekati oleh seorang wanita yang ingin menyewa perusahaan Strike untuk menyelidiki hilangnya ibunya, Margot Bamborough, seorang dokter umum di Clerkenwell , London, hampir 40 tahun sebelumnya, pada 11 Oktober 1974. Sebagai hasil dari kesuksesan mereka sebelumnya, mitra bisnis Strike dan Robin kini mempekerjakan tiga penyelidik kontrak dan seorang manajer kantor. Keduanya menghadapi masalah masing-masing: Serangan karena penyakit bibinya, ancaman bunuh diri dari mantan tunangannya Charlotte (sekarang sudah menikah dan ibu dari dua anak), dan upaya saudara tirinya untuk memaksanya menghadiri pesta untuk menghormati bintang rocknya. ayah kandung Johnny Rokeby; Robin atas kerasnya Matthew dalam perceraian mereka, PTSD yang terus berlanjut , dan kehidupan pribadinya yang tidak menentu, menjadi fokus yang lebih jelas karena saudara laki-lakinya dan istrinya memiliki anak pertama mereka.",
        novelPic: "assets/troubled.png", novelDate: "September 2020", novelContent: '"Kau asli Cornwall, lahir dan dibesarkan di Cornwall," Dave Polworth berkata dengan jengkel. "Bahkan nama aslimu sebenarnya bukan Strike. Kalau mau adil, namamu seharusnya Nancarrow. Lalu kau menyebut dirimu English?" The Victory Inn penuh sesak pada malam bulan Agustus yang hangat ini sehingga para pengunjung meluber ke luar, ke undak-undakan batu lebar yang menurun ke pantai. Polworth dan Strike duduk di meja sudut, menikmati beberapa pint bir untuk merayakan ulang tahun Polworth yang ke-39. Topik nasionalisme Cornwall telah menguasai pembicaraan mereka selama dua puluh menit terakhir, yang bagi Strike rasanya lama sekali. "Hmm, apakah aku menyebut diriku English?" katanya seraya merenung. "Tidak, barangkali aku menyebut diriku British." "Ah, keparat," umpat Polworth, temperamennya yang berangasan ter- pancing. "Kau cuma mau memanas-manasiku." Kedua kawan itu sangat kontras secara fisik. Polworth pendek dan langsing seperti joki, cokelat dan keriput dini akibat terpaan cuaca, kulit kepalanya yang terbakar matahari tampak di sela-sela rambutnya yang menipis. Kausnya kusut, sepertinya tadi dicomot begitu saja dari lantai atau dari keranjang cucian, dan celana jinsnya robek. Di lengan bawah kiri terdapat tato hitam- putih salib St. Piran; di tangan kanan ada codet yang dalam, kenang- kenangan dari pertemuan jarak dekat dengan seekor hiu. Strike mirip petinju yang sudah kendor-yang memang begitulah kenyataannya; perawakannya raksasa, hampir dua meter tingginya, dengan hidung agak bengkok dan rambut ikal rapat berwarna gelap. Tidak ada tato di  tubuhnya, dan kendati dagunya senantiasa dibayang-bayangi cambang gelap, pembawaannya rapi dan resik, khas mantan polisi atau militer. "Kau lahir di sini," kata Polworth berkeras. "Jadi kau Cornish." "Masalahnya, kalau pakai ukuran itu, berarti kau Brummie."'
        '"Aaah, keparat!" Polworth memaki lagi, kali ini benar-benar tersinggung. "Aku sudah tinggal di sini sejak umur dua bulan dan nama ibuku Trevelyan. Itulah identitas apa yang kaurasakan di sini." Polworth memukul dada di bagian jantungnya. "Keluarga ibuku sudah berabad-abad diam di Cornwall-" "Yah, bagiku, tanah dan darah tidak pernah—" "Kau sudah dengar survei terakhir?" Polworth memotong ucapan Strike. "Pada pertanyaan tentang asal-usul etnis, setengahnya—setengah!— mencentang Cornish, bukan English. Kenaikan yang besar sekali.” "Baguslah," ucap Strike. "Lalu apa lagi habis ini? Pilihan antara Dumnonia dan Romawi?" "Terus saja ngoceh sok tahu," kata Polworth. "Lihat saja bagaimana nanti. Kau sudah kelamaan di London, boy... Tidak ada salahnya bangga dengan asal-usulmu. Tidak ada salahnya masyarakat mau merebut kembali kekuasaan dari Westminster. Lihat saja tahun depan, mulai dari Skotlandia. Begitu Skotlandia merdeka, semua akan terpicu. Bangsa Kelt di seluruh negeri akan bergerak.'),
    Novels(novelID: 6, novelName: "Negeri Para Bedebah", novelGenre: "Fantasy", novelAuthor: "Tere Liye",
        novelRating: "4.4", novelHalaman: 1135, novelSinopsis: "Thomas, seorang konsultan keuangan profesional sekaligus pendiri perusahaan konsultasi keuangan terkemuka berlabel Thomas & Co. yang serba misterius. Kemampuanya dalam bidang ekonomi tidak diragukan lagi, ia sering diundang sebagai pembicara pertemuan-pertemuan besar di dunia. Namun ketika ditelusuri latar belakangnya, semua gelap. Ia seorang anak yatim piatu yang dibesarkan di asrama. Mengenyam pendidikan di sekolah berasrama tersebut sebelum menyelesaikan master ekonomi di luar negeri. Tidak ada yang tahu, keluarganya. Di lain sisi, sebuah bank nasional bernama bank Semesta tersandung masalah keuangan yang serius. Pemiliknya, Mr Liem terbukti melakukan pelanggaran terhadap bisnis perbankan yang dimilikinya tersebut. Oleh karena itu, sejak malam polisi telah mengepung rumahnya, tetapi karena istri tuan rumah tiba-tiba pingsan, penangkapan itu urung dilakukan. Dalam keadaan terdesak itulah, Mr Liem melalui pesuruhnya Ram menghubungi Thomas. Bukan, bukan karena Thomas seorang konsultan keuangan, melainkan karena Thomas memiliki hubungan darah dengan Mr Liem. Sebenarnya Thomas enggan membantu, ia semenjak tragedi pada masa lalu memutuskan membenci Mr Liem. Namun mendengar tante Liem dalam kondisi yang buruk, maka tidak ada jalan lain selain menolongnya. Mulai dari sini, latar belakang keluarga Thomas mulai terbongkar. agi-lagi wartawan mereka datang terlambat di gedung konferensi, dan aku sudah menumpang taksi bergegas menuju bandara. Editor itu kembali terburu-buru menelepon, bilang mereka sudah berusaha mengirimkan wartawan terbaik mengejarku ke Eropa, tetapi jadwalku terlalu padat untuk diikuti.",
        novelPic: "assets/negeriparabedebah.png", novelDate: "Juli 2012", novelContent: 'PESAWAT berbadan besar yang kutumpangi melaju cepat meninggalkan London. Penerbangan ini nonstop menuju Singapura. Gadis dengan rambut dikucir dan seperangkat touchscreen di tangan, berisi corat-coret daftar pertanyaan, tersenyum gugup di kursi berlapis kulit asli di sebelahku. Aku sedang tidak berselera untuk tersenyum, cukup menyeringai, menatapnya datar. "Silakan," kataku. "Maaf, wawancara ini sudah berkali-kali ditunda. Kami sudah berusaha menyesuaikan jadwal. Tapi begitulah, tidak mudah mengejar kesibukan Anda." Dia sedikit percaya diri tampaknya. Senyumnya lebih baik. Aku mengangguk. Aku tahu, tidak perlu dijelaskan. Janji pertama bertemu di Jakarta kemarin pagi batal karena aku sudah berangkat menghadiri konferensi. Editor senior majalah mingguan itu spesial meneleponku, minta maaf, bilang wawancara ini amat penting, waktunya mendesak, pembaca setia mereka ingin tahu bagaimana cara terbaik menyikapi turbulensi ekonomi dunia saat ini. Apa pun akan mereka lakukan mendapatkan untuk materi wawancara, termasuk menyusulku ke London. Baiklah, aku memberikan waktu satu jam selepas konferensi.'),

  ];

  Novels.formMap(dynamic ojb){
    this.novelID = ojb['novelID'];
    this.novelName = ojb['novelName'];
    this.novelGenre = ojb['novelGenre'];
    this.novelAuthor = ojb['novelAuthor'];
    this.novelRating = ojb['novelRating'];
    this.novelHalaman = ojb['novelHalaman'];
    this.novelSinopsis = ojb['novelSinopsis'];
    this.novelPic = ojb['novelPic'];
    this.novelDate = ojb['novelDate'];
    this.novelContent = ojb['novelContent'];


  }

  Map<String, dynamic> toMap(){
    var map = <String,dynamic>{
      'novelName' : novelName,
      'novelGenre' : novelGenre,
      'novelAuthor' : novelAuthor,
      'novelRating' : novelRating,
      'novelHalaman' : novelHalaman,
      'novelSinopsis' : novelSinopsis,
      'novelPic' : novelPic,
      'novelDate' : novelDate,
      'novelContent' : novelContent,
    };
    return map;
  }

}